#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : async-timeout
Version  : 4.0.1
Release  : 28
URL      : https://files.pythonhosted.org/packages/ce/cf/9452ab2a5936f96aa94e3c1cf21e8038b643cd27f33aeebc3aea5d25bcd1/async-timeout-4.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/ce/cf/9452ab2a5936f96aa94e3c1cf21e8038b643cd27f33aeebc3aea5d25bcd1/async-timeout-4.0.1.tar.gz
Summary  : Timeout context manager for asyncio programs
Group    : Development/Tools
License  : Apache-2.0
Requires: async-timeout-license = %{version}-%{release}
Requires: async-timeout-python = %{version}-%{release}
Requires: async-timeout-python3 = %{version}-%{release}
Requires: typing_extensions
BuildRequires : buildreq-distutils3
BuildRequires : setuptools
BuildRequires : wheel

%description
async-timeout
=============
.. image:: https://travis-ci.com/aio-libs/async-timeout.svg?branch=master
:target: https://travis-ci.com/aio-libs/async-timeout
.. image:: https://codecov.io/gh/aio-libs/async-timeout/branch/master/graph/badge.svg
:target: https://codecov.io/gh/aio-libs/async-timeout
.. image:: https://img.shields.io/pypi/v/async-timeout.svg
:target: https://pypi.python.org/pypi/async-timeout
.. image:: https://badges.gitter.im/Join%20Chat.svg
:target: https://gitter.im/aio-libs/Lobby
:alt: Chat on Gitter

%package license
Summary: license components for the async-timeout package.
Group: Default

%description license
license components for the async-timeout package.


%package python
Summary: python components for the async-timeout package.
Group: Default
Requires: async-timeout-python3 = %{version}-%{release}

%description python
python components for the async-timeout package.


%package python3
Summary: python3 components for the async-timeout package.
Group: Default
Requires: python3-core
Provides: pypi(async_timeout)
Requires: pypi(typing_extensions)

%description python3
python3 components for the async-timeout package.


%prep
%setup -q -n async-timeout-4.0.1
cd %{_builddir}/async-timeout-4.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1636645794
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/async-timeout
cp %{_builddir}/async-timeout-4.0.1/LICENSE %{buildroot}/usr/share/package-licenses/async-timeout/2a8f799cf5d5f9ad7c402c17b6a460580bb806d2
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/async-timeout/2a8f799cf5d5f9ad7c402c17b6a460580bb806d2

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
